### ISSUE TITLE
Mitsubishi Heat Recovery-Lossnay Missing On-Off Control Button

### ISSUE THREAD

**Issue by cneagoe1973** [ojkaas/MELCloud#1]
Hello,
First of all I want to thank you for your good job making this Add-on for HomeAsssitant.
All work very well , the Add-on found my Mitsubishi Heat Recovery-Lossnay  and created the most important feature but only one missing :  ON/OFF Control Button
Can you research into it and add it to the next version ?
Thank you very much,
Catalin
P.S. If you need more info , or remote control on my HomeAssist let me know
![Screenshot 2024-01-27 132244](https://github.com/ojkaas/MELCloud/assets/61342792/9f498c2a-ba3c-4842-83d2-1f4c90755a10)
![Screenshot 2024-01-27 132346](https://github.com/ojkaas/MELCloud/assets/61342792/d0de085e-7842-4a98-85ef-7f56d8929693)

**Comment by ojkaas** [comment]
Hi! I added the power switch to the new version!

One small note, you wont actually directly see that the ERV is off, because the state updates are still rate limited, and as I am not a python expert I am not touching that stuff for now :)

**Comment by ojkaas** [comment]
Closing this
