### ISSUE TITLE
We have detected excessive traffic from your account, your access to the service has been limited for a few hours.

### ISSUE THREAD

**Issue by cneagoe1973** [ojkaas/MELCloud#2]
Hello,
I know you struggle to find the right amount of time to interogate  the Mel->cloud, please can you increase the time because I think they change it again.
I'm still receive the message : "We have detected excessive traffic from your account, your access to the service has been limited for a few hours."
but after 1 ,2 hours  after i disable the add-on in homeassistant it works again until I enable it again.
Thank you,
Catalin

**Comment by loopyengineeringco** [comment]
Having the same issue.
After deleting and re-setting up the integration, it goes dead after a while.

**Comment by ojkaas** [comment]
The only thing I could think of that is different is that i tried to update the device after the power on/off switch was triggered, maybe this introduced some problems as this is not rate limitted. I have removed the update from the switch device, hope this helps!

I did not touch any of the other rate limit stuff so that is not really into my control, and if it needs to be looked at, i really need somebody to help me that has better python skills :D

**Comment by ojkaas** [comment]
I actually saw in the official melcloud integration that they are struggling with this problem too as mitsubishi made the polling rates cut off much more strict. I copied over the changes they did to reduce the polling rate to every 5 minutes.

**Comment by cneagoe1973** [comment]
Hello again,
please can you double check the last update version  because we have some errors in line 444 in 
"/usr/src/homeassistant/homeassistant/config_entries.py

see below the logs when I tried to add an entry:

2024-02-14 07:33:42.096 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry xxxxxxxx@gmail.com for melcloudwitherv
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 444, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/melcloudwitherv/__init__.py", line 70, in async_setup_entry
    mel_devices = await mel_devices_setup(hass, conf[CONF_TOKEN])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/melcloudwitherv/__init__.py", line 174, in mel_devices_setup
    all_devices = await get_devices(
                        ^^^^^^^^^^^^
TypeError: get_devices() got an unexpected keyword argument 'user_update_interval'
